import{A as d,S as l,N as u,a as p,K as f,b as w}from"./assets/vendor-PocSSiV5.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))n(o);new MutationObserver(o=>{for(const s of o)if(s.type==="childList")for(const r of s.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&n(r)}).observe(document,{childList:!0,subtree:!0});function i(o){const s={};return o.integrity&&(s.integrity=o.integrity),o.referrerPolicy&&(s.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?s.credentials="include":o.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(o){if(o.ep)return;o.ep=!0;const s=i(o);fetch(o.href,s)}})();document.addEventListener("DOMContentLoaded",()=>{document.querySelectorAll(".accordion-content").forEach(e=>{e.style.maxHeight="0px",e.style.opacity="0",e.style.overflow="hidden"}),new d(".accordion",{duration:400,showMultiple:!0,elementClass:"accordion-item",triggerClass:"accordion-button",panelClass:"accordion-content",onOpen:e=>{let i=e.querySelector(".accordion-content"),n=e.querySelector(".accordion-button use");i&&(i.style.maxHeight=i.scrollHeight+"px",i.style.opacity="1",i.style.overflow="visible"),n&&n.setAttribute("href","../img/icon.svg#icon-up")},onClose:e=>{let i=e.querySelector(".accordion-content"),n=e.querySelector(".accordion-button use");i&&(i.style.maxHeight="0px",i.style.opacity="0",i.style.overflow="hidden"),n&&n.setAttribute("href","../img/icon.svg#icon-down")}})});const c=new l(".about-skills-swiper",{slidesPerView:6,slidesPerGroup:1,loop:!0,modules:[u,p],navigation:{nextEl:".about-skills-btn"},autoplay:{delay:2e3},keyboard:{enabled:!1},mousewheel:{invert:!0},breakpoints:{320:{slidesPerView:2},768:{slidesPerView:3},1440:{slidesPerView:6}}});document.addEventListener("keydown",t=>{t.key==="ArrowRight"?c.slideNext():t.key==="ArrowLeft"&&c.slidePrev()});new d(".about-info",{duration:500,showMultiple:!0,openOnInit:[0],elementClass:"about-info-item",triggerClass:"about-info-btn",panelClass:"about-info-content",activeClass:"is-active"});new l(".reviews",{slidesPerView:4,spaceBetween:16,slidesPerGroup:1,modules:[u,f],navigation:{nextEl:".reviews-btn-next",prevEl:".reviews-btn-prev"},keyboard:{enabled:!0,pageUpDown:!0},mousewheel:{invert:!0},breakpoints:{310:{slidesPerView:1},768:{slidesPerView:2},1440:{slidesPerView:4,spaceBetween:10}}});const a={list:document.querySelector(".reviews-list")};document.addEventListener("DOMContentLoaded",async()=>{try{const t=await m(),e=v(t);a.list.innerHTML=e}catch(t){a.list.innerHTML='<p class="reviews-err">---Not found---</p>',console.log(t)}});async function m(){return(await w.get("https://portfolio-js.b.goit.study/api/reviews")).data}function g(t){const{author:e,avatar_url:i,review:n}=t;return`<li class="reviews-item swiper-slide">
              <img
                class="reviews-img"
                src="${i}"
                alt="foto author"
              />
              <h2 class="reviews-name">${e}</h2>
              <p class="reviews-txt">${n}</p>
            </li>`}function v(t){return t.map(g).join("")}(()=>{const t={closeModalBtn:document.querySelector("[data-menu-close]"),modal:document.querySelector("[data-menu]")};console.log(t.closeModalBtn),t.closeModalBtn.addEventListener("click",e);function e(){console.log(t.modal),t.modal.classList.toggle("is-open")}})();document.addEventListener("DOMContentLoaded",function(){const t=document.querySelector(".custom-swiper-prev"),e=document.querySelector(".custom-swiper-next"),i=document.querySelector(".projects-swiper");if(!i||!t||!e)return;const n=new l(i,{slidesPerView:1,spaceBetween:20,grabCursor:!0,allowTouchMove:!0,simulateTouch:!0,touchRatio:1,touchAngle:45,resistance:!0,resistanceRatio:.5,speed:300,loop:!1,navigation:{nextEl:e,prevEl:t},on:{init:function(){o(this)},slideChange:function(){o(this)}}});function o(s){t.disabled=s.isBeginning,e.disabled=s.isEnd,t.classList.toggle("inactive",s.isBeginning),e.classList.toggle("inactive",s.isEnd)}t.addEventListener("click",()=>n.slidePrev()),e.addEventListener("click",()=>n.slideNext())});
//# sourceMappingURL=index.js.map
