import{S as a,N as c,P as u,K as d,a as p}from"./assets/vendor-D3gR0pi4.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(e){if(e.ep)return;e.ep=!0;const s=i(e);fetch(e.href,s)}})();new a(".skills-swiper",{slidesPerView:6,slidesPerGroup:1,loop:!0,modules:[c,u,d],navigation:{nextEl:".about-skills-btn"},keyboard:{enabled:!0,pageUpDown:!0},mousewheel:{invert:!0},breakpoints:{320:{slidesPerView:2},768:{slidesPerView:3},1440:{slidesPerView:6}}});new a(".swiper",{slidesPerView:4,spaceBetween:16,slidesPerGroup:1,modules:[c,u,d],navigation:{nextEl:".reviews-btn-next",prevEl:".reviews-btn-prev"},keyboard:{enabled:!0,pageUpDown:!0},mousewheel:{invert:!0},breakpoints:{310:{slidesPerView:1},740:{slidesPerView:2},1024:{slidesPerView:3},1440:{slidesPerView:4,spaceBetween:10}}});const l={list:document.querySelector(".reviews-list")};document.addEventListener("DOMContentLoaded",async()=>{try{const t=await w(),r=m(t);l.list.innerHTML=r}catch(t){l.list.innerHTML='<p class="reviews-err">---Not found---</p>',console.log(t)}});async function w(){return(await p.get("https://portfolio-js.b.goit.study/api/reviews")).data}function f(t){const{author:r,avatar_url:i,review:o}=t;return`<li class="reviews-item swiper-slide">
              <img
                class="reviews-img"
                src="${i}"
                alt="foto author"
              />
              <h2 class="reviews-name">${r}</h2>
              <p class="reviews-txt">${o}</p>
            </li>`}function m(t){return t.map(f).join("")}(()=>{const t={closeModalBtn:document.querySelector("[data-menu-close]"),modal:document.querySelector("[data-menu]")};console.log(t.closeModalBtn),t.closeModalBtn.addEventListener("click",r);function r(){console.log(t.modal),t.modal.classList.toggle("is-open")}})();
//# sourceMappingURL=index.js.map
