import{S as c,a}from"./assets/vendor-CSA7w3Pc.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();new c(".swiper",{slidesPerView:4,spaceBetween:16,slidesPerGroup:1,navigation:{nextEl:".reviews-btn-next",prevEl:".reviews-btn-prev"},keyboard:{enabled:!0,pageUpDown:!0},mousewheel:{invert:!0},breakpoints:{310:{slidesPerView:1},740:{slidesPerView:2},1024:{slidesPerView:3},1440:{slidesPerView:4,spaceBetween:10}}});const l={list:document.querySelector(".reviews-list")};document.addEventListener("DOMContentLoaded",async()=>{try{const t=await u(),s=p(t);l.list.innerHTML=s}catch(t){l.list.innerHTML='<p class="reviews-err">---Not found---</p>',console.log(t)}});async function u(){return(await a.get("https://portfolio-js.b.goit.study/api/reviews")).data}function d(t){const{author:s,avatar_url:i,review:o}=t;return`<li class="reviews-item swiper-slide">
              <img
                class="reviews-img"
                src="${i}"
                alt="foto author"
              />
              <h2 class="reviews-name">${s}</h2>
              <p class="reviews-txt">${o}</p>
            </li>`}function p(t){return t.map(d).join("")}(()=>{const t={closeModalBtn:document.querySelector("[data-menu-close]"),modal:document.querySelector("[data-menu]")};console.log(t.closeModalBtn),t.closeModalBtn.addEventListener("click",s);function s(){console.log(t.modal),t.modal.classList.toggle("is-open")}})();
//# sourceMappingURL=index.js.map
